# Generated by Django 5.0.6 on 2025-03-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_comment_statuscomment'),
        ('events', '0002_comment_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='EventComment',
        ),
    ]
