# Generated by Django 5.0.6 on 2025-10-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_recommendation_alter_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
    ]
