# Generated by Django 5.0.6 on 2025-10-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventcomment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_phone_number',
            field=models.CharField(default=421857645, help_text='Guests can use this number to contact the host for this event.', max_length=20, verbose_name='Host Mobile Number'),
            preserve_default=False,
        ),
    ]
