# Generated by Django 5.0.6 on 2025-11-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_host_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='preferred_age_band',
            field=models.CharField(choices=[('none', 'None'), ('under_25', 'Under 25'), ('25_35', '25 - 35'), ('36_over', '36 and over')], default='none', max_length=20, verbose_name='Preferred Age Band'),
        ),
    ]
