FROM python:3.10-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Set container timezone to Australia/Sydney
RUN ln -snf /usr/share/zoneinfo/Australia/Sydney /etc/localtime && echo "Australia/Sydney" > /etc/timezone

COPY . .

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "friendi.wsgi:application"]