"""
Django settings for foodiefriend project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from socket import gethostbyname
from socket import gethostname
import environ

# Load the appropriate .env file
env = environ.Env()
if os.environ.get("DJANGO_ENV") != "production":
    env.read_env(".env.development")
else:
    env.read_env(".env.production")
# DJANGO_ENV = os.environ.get("DJANGO_ENV", "development").lower()

# if DJANGO_ENV == "production":
#     env_file = ".env.production"
#     print("In production")
# else:
#     env_file = ".env.development"
#     print("In development")

# env.read_env()

# End load the appropriate .env file

# GENERAL SETTINGS

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)
print("DEBUG: ", DEBUG)

LOGIN_URL = "/accounts/login/"

TIME_ZONE = "Australia/Sydney"

USE_TZ = True

DOMAIN = env("DOMAIN")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")


ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost"])
ALLOWED_HOSTS.append(gethostbyname(gethostname()))

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "http://127.0.0.1:8000",
    ],
)
# end general settings

# twilio settings

# Replace with your actual credentials or use environment variables
TWILIO_ACCOUNT_SID = env("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = env("TWILIO_AUTH_TOKEN")
TWILIO_FROM_NUMBER = env("TWILIO_FROM_NUMBER")

# end twilio settings

# stripe

STRIPE_PUBLIC_KEY = env("STRIPE_PUBLIC_KEY")
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET")

# end stripe


# django q settings
Q_CLUSTER = {
    "name": "DjangoQ",
    "workers": 4,
    "recycle": 500,
    "timeout": 60,
    "retry": 90,
    "queue_limit": 50,
    "bulk": 10,
    "catch_up": False,
    "broker_class": "django_q.brokers.redis_broker.Redis",
    "redis": {
        "host": env("REDIS_HOST", default="127.0.0.1"),
        "port": env.int("REDIS_PORT", default=6379),
        "db": env.int("REDIS_DB", default=0),
    },
}

# end django q settings

# reCAPTCHA keys
RECAPTCHA_PUBLIC_KEY = env("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = env("RECAPTCHA_PRIVATE_KEY")

# end reCAPTCHA keys

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django_recaptcha",
    # 'django.contrib.sites',
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django_q",
    "app",
    "photos",
    "friends",
    "notifications",
    "direct_messages",
    "events",
    # 'debug_toolbar',
    # 3rd party libraries
    "multiselectfield",
    "storages",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
]

# DEBUG_TOOLBAR_CONFIG = {
#     'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
# }

MIDDLEWARE = [
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    # "friendi.middleware.UnderConstructionMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "friendi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "app", "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "app.context_processors.notifications_count",
            ],
        },
    },
]


WSGI_APPLICATION = "friendi.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "dbmaster_test",
        "USER": "postgres",
        "PASSWORD": "Sydney45!",
        "HOST": "ls-10d6a5c132f12f9ff9252d45d053b2b7a158f49f.clqm42sjkslc.ap-southeast-2.rds.amazonaws.com",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

# STATIC FILES DEVELOPMENT (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
# MEDIA_URL = "media/"
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# end STATIC FILES DEVELOPMENT (CSS, JavaScript, Images)

# S3 BUCKETS CONFIG STATIC FILES

AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME")

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
DEFAULT_FILE_STORAGE = "friendi.s3utils.MediaStorage"  # storage for media files
STATICFILES_STORAGE = (
    "storages.backends.s3boto3.S3Boto3Storage"  # storage for static files
)

# end S3 BUCKETS CONFIG STATIC FILES

# Google maps
GOOGLE_MAPS_API_KEY = env("GOOGLE_MAPS_API_KEY")

# end google maps

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# SMTP Configuration

EMAIL_BACKEND = env("EMAIL_BACKEND")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env.int("EMAIL_PORT")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")

# end

# DJANGO ALLAUTH
LOGIN_REDIRECT_URL = "home"

ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID"),
            "secret": env("GOOGLE_CLIENT_SECRET"),
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "OAUTH_PKCE_ENABLED": True,
        "VERIFIED_EMAIL": True,
    },
    "facebook": {
        "APP": {
            "client_id": env("FACEBOOK_CLIENT_ID"),
            "secret": env("FACEBOOK_CLIENT_SECRET"),
            "key": "",
        },
        "SCOPE": [
            "email",
            "public_profile",
        ],
        "AUTH_PARAMS": {"auth_type": "reauthenticate"},
        "INIT_PARAMS": {"cookie": True},
        "FIELDS": [
            "first_name",
            "last_name",
        ],
        "METHOD": "oauth2",
        "VERIFIED_EMAIL": False,
        "VERSION": "v20.0",
    },
}

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# SITE_ID=1

# ACCOUNT SETTINGS
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 7
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
SOCIALACCOUNT_ADAPTER = "app.adapters.MySocialAccountAdapter"
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None (causes problems with unique usernames during the signup process)

# SOCIAL ACCOUNT SETTINGS
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = False


ACCOUNT_FORMS = {
    "login": "app.forms.CustomLoginForm",
    "signup": "app.forms.CustomSignupForm",
    "reset_password": "app.forms.CustomResetPasswordForm",
    "reset_password_from_key": "app.forms.CustomResetPasswordKeyForm",
}
# end allauth

# logging

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # keep Django's default loggers
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",  # You can change to DEBUG for more verbosity
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django_q": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "events": {  # Replace with your actual app name if needed
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# end logging
