# Generated by Django 5.0.6 on 2025-03-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='fire_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='heart_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='laugh_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
