# Generated by Django 5.0.6 on 2025-03-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_reaction_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusupdate',
            old_name='fire_count',
            new_name='like_count',
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='heart_count',
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='laugh_count',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', '❤️')], max_length=10),
        ),
    ]
