# Generated by Django 5.0.6 on 2025-03-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_fire_count_statusupdate_like_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='reaction_type',
        ),
        migrations.AddField(
            model_name='reaction',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
