# Generated by Django 5.0.6 on 2025-03-03 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_reaction_reaction_type_reaction_is_liked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusupdate',
            name='like_count',
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
