# Generated by Django 5.0.6 on 2025-03-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_statusupdate_like_count_statusupdate_liked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='status_images/'),
        ),
    ]
