# Generated by Django 5.0.6 on 2025-06-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_comment_statuscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_band',
            field=models.CharField(choices=[('rather_not_say', 'Leave blank'), ('under_25', 'Under 25'), ('25_to_35', '25 - 35'), ('36_and_over', '36 and over')], default='rather_not_say', max_length=20, null=True),
        ),
    ]
