# Generated by Django 5.0.6 on 2025-06-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_email_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_tour',
            field=models.BooleanField(default=False),
        ),
    ]
