# Generated by Django 5.0.6 on 2025-10-23 00:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profile_has_seen_tour'),
        ('photos', '0002_remove_photo_album_photo_status_delete_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='profile_gallery/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='profile',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='app.profile'),
            preserve_default=False,
        ),
    ]
