# Generated by Django 5.0.6 on 2025-10-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_options_remove_photo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
