# Generated by Django 5.0.6 on 2025-11-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='profile_gallery/thumbnails/'),
        ),
    ]
